#!/usr/bin/env python3
"""Render Loki Ruler rules and Perses dashboards from queries/*.yaml.

Inputs:
  platform/observability/queries/catalog.yaml
  platform/observability/queries/<cluster>/<id>.yaml

Outputs:
  platform/observability/ruler/rules.yaml
  platform/observability/perses/dashboard-<id>.yaml

Usage:
  python render.py [--check]

  --check: render to a temp dir and diff against the existing outputs.
           Exit non-zero if they differ. Suitable for CI.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

import yaml


def _str_representer(dumper, data):
    """Use literal block scalar for multi-line strings — keeps LogQL readable."""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


yaml.add_representer(str, _str_representer, Dumper=yaml.SafeDumper)


def _dump(doc) -> str:
    return yaml.safe_dump(doc, sort_keys=False, width=120, allow_unicode=True)


ROOT = Path(__file__).resolve().parent
QUERIES = ROOT / "queries"
RULER_OUT = ROOT / "ruler" / "rules.yaml"
PERSES_OUT = ROOT / "perses"


def load_queries() -> list[dict]:
    """Load every <cluster>/<id>.yaml referenced in catalog.yaml."""
    catalog = yaml.safe_load((QUERIES / "catalog.yaml").read_text())
    out = []
    for entry in catalog.get("queries", []):
        path = QUERIES / entry["file"]
        if not path.is_file():
            sys.exit(f"catalog references missing file: {entry['file']}")
        q = yaml.safe_load(path.read_text())
        if q["id"] != entry["id"]:
            sys.exit(f"id mismatch in {path}: file says {q['id']!r}, "
                     f"catalog says {entry['id']!r}")
        if q["cluster"] != entry["cluster"]:
            sys.exit(f"cluster mismatch in {path}")
        out.append(q)
    return out


def render_ruler(queries: list[dict], outdir: Path) -> None:
    """Emit one Loki Ruler group per cluster, with all alerts for that cluster.

    Loki Ruler accepts the Prometheus rules format verbatim. We only emit
    alerting rules here (no recording rules yet).
    """
    groups: dict[str, list[dict]] = defaultdict(list)
    for q in queries:
        if "alert" not in q:
            continue
        a = q["alert"]
        rule = {
            "alert": a["name"],
            "expr": q["expr"].rstrip() + " " + a["condition"],
            "for": a["for"],
            "labels": {
                "severity": a["severity"],
                "cluster": q["cluster"],
            },
            "annotations": {
                "summary": a["summary"],
                "description": q["description"].rstrip(),
                "runbook": q.get("runbook", ""),
            },
        }
        groups[q["cluster"]].append(rule)

    doc = {
        "groups": [
            {
                "name": f"observability-{cluster}",
                "interval": "1m",
                "rules": rules,
            }
            for cluster, rules in sorted(groups.items())
        ]
    }
    out = outdir / "ruler" / "rules.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# GENERATED by platform/observability/render.py — do not edit.\n"
        "# Source: platform/observability/queries/<cluster>/*.yaml\n\n"
        + _dump(doc)
    )


def render_perses(queries: list[dict], outdir: Path) -> None:
    """Emit one Perses Dashboard YAML per dashboard id referenced.

    Loki speaks the Prometheus query API for LogQL metric queries, so we
    use the PrometheusTimeSeriesQuery plugin pointed at a `loki-<cluster>`
    datasource. The datasource itself is provisioned separately (see the
    deployment plan in docs/observability-DESIGN.md).
    """
    by_dashboard: dict[str, list[dict]] = defaultdict(list)
    for q in queries:
        if "panel" not in q:
            continue
        by_dashboard[q["panel"]["dashboard"]].append(q)

    perses_dir = outdir / "perses"
    perses_dir.mkdir(parents=True, exist_ok=True)

    for dashboard_id, qs in sorted(by_dashboard.items()):
        panels = {}
        layout_items = []
        for i, q in enumerate(qs):
            panel_id = q["id"].replace("-", "_")
            panels[panel_id] = panel_for(q)
            layout_items.append({
                "x": 0,
                "y": i * 8,
                "width": 24,
                "height": 8,
                "content": {"$ref": f"#/spec/panels/{panel_id}"},
            })
        doc = {
            "kind": "Dashboard",
            "metadata": {"name": dashboard_id, "project": "fagor"},
            "spec": {
                "display": {"name": dashboard_id},
                "duration": "1h",
                "panels": panels,
                "layouts": [{
                    "kind": "Grid",
                    "spec": {"display": {"title": "Main"}, "items": layout_items},
                }],
            },
        }
        out = perses_dir / f"dashboard-{dashboard_id}.yaml"
        out.write_text(
            "# GENERATED by platform/observability/render.py — do not edit.\n\n"
            + _dump(doc)
        )


def panel_for(q: dict) -> dict:
    """Build a single Perses panel spec from a query entry."""
    p = q["panel"]
    plugin_kind = {
        "timeseries": "TimeSeriesChart",
        "stat": "StatChart",
        "table": "Table",
    }.get(p["type"], "TimeSeriesChart")

    plugin_spec: dict = {}
    if p["type"] == "timeseries" and p.get("thresholds"):
        plugin_spec["thresholds"] = {
            "steps": [
                {"value": t["value"], "color": t["color"]}
                for t in p["thresholds"]
            ],
        }

    return {
        "kind": "Panel",
        "spec": {
            "display": {"name": q["title"]},
            "plugin": {"kind": plugin_kind, "spec": plugin_spec},
            "queries": [{
                "kind": "TimeSeriesQuery",
                "spec": {
                    "plugin": {
                        "kind": "PrometheusTimeSeriesQuery",
                        "spec": {
                            "datasource": {
                                "kind": "PrometheusDatasource",
                                "name": f"loki-{q['cluster']}",
                            },
                            "query": q["expr"].rstrip(),
                            "seriesNameFormat": p.get("legend", ""),
                        },
                    },
                },
            }],
        },
    }


def diff_against(actual: Path, generated: Path) -> int:
    """Return 0 if `actual` matches `generated`, 1 otherwise. Prints the diff."""
    rc = subprocess.call(
        ["diff", "-ruN", str(actual), str(generated)],
        stdout=sys.stdout, stderr=sys.stderr,
    )
    return rc


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="render to a tmp dir and diff against current outputs; "
                         "exit non-zero if they differ")
    args = ap.parse_args()

    queries = load_queries()

    if args.check:
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            render_ruler(queries, tmp)
            render_perses(queries, tmp)
            rc = 0
            for sub in ("ruler", "perses"):
                actual = ROOT / sub
                generated = tmp / sub
                if not actual.exists() and not any(generated.iterdir()):
                    continue
                if diff_against(actual, generated):
                    rc = 1
            return rc

    render_ruler(queries, ROOT)
    render_perses(queries, ROOT)
    print(f"rendered {len(queries)} quer{'y' if len(queries)==1 else 'ies'} -> "
          f"{RULER_OUT.relative_to(ROOT)}, "
          f"{PERSES_OUT.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
